version: "3"

services:

  consul:
    container_name: consul
    image: hashicorp/consul:1.20
    ports:
      - "8555:8500"
    volumes:
      - qw_consul_data:/consul/data
      - ./configs/consul.hcl:/consul/config/consul.hcl
    networks:
      - qw_stage_gateway-net

  api-gateway:
    container_name: gateway
    image: davidmovas/quizwars-api-gateway:latest
    environment:
      LOCAL: ${LOCAL}
      LOG_LEVEL: ${LOG_LEVEL}
      HTTP_PORT: ${HTTP_PORT}
      TCP_PORT: ${TCP_PORT}
      GRPC_PORT: ${GRPC_PORT}
      WS_PORT: ${WS_PORT}
      START_TIMEOUT: ${START_TIMEOUT}
      SHUTDOWN_TIMEOUT: ${SHUTDOWN_TIMEOUT}
      CONSUL_URL: ${CONSUL_URL}
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${TCP_PORT}:${TCP_PORT}
      - ${GRPC_PORT}:${GRPC_PORT}
      - ${WS_PORT}:${WS_PORT}
    networks:
      - qw_stage_gateway-net
    depends_on:
      - consul

networks:
  qw_stage_gateway-net:

volumes:
  qw_consul_data: