version: "3"

services:

  questions-service:
    image: davidmovas/quizwars-questions-service:latest
    volumes:
      - ./configs/questions.yaml:/app/config/config.yaml
    networks:
      - qw_stage_questions-net
      - qw_stage_gateway-net
    depends_on:
      questions-postgres:
        condition: service_healthy

  questions-redis:
    container_name: questions-redis
    image: redis:7.4.2-alpine
    ports:
      - ${REDIS_DB_PORT}:6379
    volumes:
      - qw_stage_questions_redis_data:/data
    networks:
      - qw_stage_questions-net

  questions-postgres:
    container_name: questions-postgres
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: ${QUESTIONS_DB_USERNAME}
      POSTGRES_PASSWORD: ${QUESTIONS_DB_PASSWORD}
      POSTGRES_DB: ${QUESTIONS_DB_NAME}
    restart: on-failure
    ports:
      - ${QUESTIONS_DB_PORT}:5432
    volumes:
      - qw_stage_questions_postgres_data:/var/lib/postgresql/data
    networks:
      - qw_stage_questions-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname ${QUESTIONS_DB_NAME} --username ${QUESTIONS_DB_USERNAME}" ]
      interval: 2s
      timeout: 15s

  questions-migrator:
    image: davidmovas/quizwars-migrations:questions-latest
    command:
      - migrate
      - --conn-string
      - postgres://${QUESTIONS_DB_USERNAME}:${QUESTIONS_DB_PASSWORD}@questions-postgres:5432/${QUESTIONS_DB_NAME}
      - --migrations
      - /migrations
    networks:
      - qw_stage_questions-net
    depends_on:
      questions-postgres:
        condition: service_healthy

networks:
  qw_stage_gateway-net:
  qw_stage_questions-net:

volumes:
  qw_stage_questions_postgres_data:
  qw_stage_questions_redis_data: