version: "3"

services:

  questions-service:
    build:
      context: ../../questions-service
      dockerfile: Dockerfile
    environment:
      LOCAL: ${LOCAL}
      NAME: ${NAME}
      ADDRESS: ${ADDRESS}
      GRPC_PORT: ${GRPC_PORT}
      START_TIMEOUT: ${START_TIMEOUT}
      SHUTDOWN_TIMEOUT: ${SHUTDOWN_TIMEOUT}
      CONSUL_URL: ${CONSUL_URL}
      POSTGRES_URL: postgres://${QUESTIONS_DB_USERNAME}:${QUESTIONS_DB_PASSWORD}@questions-postgres:5432/${QUESTIONS_DB_NAME}
      REDIS_URL: questions-redis:6379
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
    networks:
      - qw_questions-net
      - qw_gateway-net
    depends_on:
      - questions-postgres

  questions-redis:
    container_name: questions-redis
    image: redis:7.4.2-alpine
    ports:
      - ${REDIS_DB_PORT}:6379
    volumes:
      - qw_questions_redis_data:/data
    networks:
      - qw_questions-net

  questions-postgres:
    container_name: questions-postgres
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: ${QUESTIONS_DB_USERNAME}
      POSTGRES_PASSWORD: ${QUESTIONS_DB_PASSWORD}
      POSTGRES_DB: ${QUESTIONS_DB_NAME}
    restart: on-failure
    ports:
      - ${QUESTIONS_DB_PORT}:5432
    volumes:
      - qw_questions_postgres_data:/var/lib/postgresql/data
    networks:
      - qw_questions-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname ${QUESTIONS_DB_NAME} --username ${QUESTIONS_DB_USERNAME}" ]
      interval: 2s
      timeout: 15s

  questions-migrator:
    build:
      context: ../../questions-service
      dockerfile: tern.dockerfile
    command:
      - migrate
      - --conn-string
      - postgres://${QUESTIONS_DB_USERNAME}:${QUESTIONS_DB_PASSWORD}@questions-postgres:5432/${QUESTIONS_DB_NAME}
      - --migrations
      - /migrations
    networks:
      - qw_questions-net
    depends_on:
      questions-postgres:
        condition: service_healthy

networks:
  qw_gateway-net:
  qw_questions-net:

volumes:
  qw_questions_postgres_data:
  qw_questions_redis_data: