version: "3"

services:

  consul:
    container_name: consul
    image: hashicorp/consul:1.20
    ports:
      - "8555:8500"      # GUI / API
      - "8600:8600/udp"  # DNS Consul (optional)
    volumes:
      - qw_consul_data:/consul/data
      - ./configs/consul.hcl:/consul/config/consul.hcl
    command: agent -dev -client=0.0.0.0 # Only for development mode
    networks:
      - qw_dev_gateway-net
      - qw_dev_monitoring-net

  api-gateway:
    container_name: gateway
    build:
      context: ../../../api-gateway
      dockerfile: Dockerfile
    environment:
      LOCAL: ${LOCAL}
      LOG_LEVEL: ${LOG_LEVEL}
      HTTP_PORT: ${HTTP_PORT}
      TCP_PORT: ${TCP_PORT}
      GRPC_PORT: ${GRPC_PORT}
      WS_PORT: ${WS_PORT}
      START_TIMEOUT: ${START_TIMEOUT}
      SHUTDOWN_TIMEOUT: ${SHUTDOWN_TIMEOUT}
      CONSUL_URL: ${CONSUL_URL}
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${TCP_PORT}:${TCP_PORT}
      - ${GRPC_PORT}:${GRPC_PORT}
      - ${WS_PORT}:${WS_PORT}
    networks:
      - qw_dev_gateway-net
      - qw_dev_monitoring-net
    depends_on:
      - consul

networks:
  qw_dev_gateway-net:
  qw_dev_monitoring-net:

volumes:
  qw_consul_data: