version: "3"

services:

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "13100:3100"
    volumes:
      - ./configs/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - qw_dev_monitoring-net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - qw_dev_logs:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - qw_dev_monitoring-net

networks:
  qw_dev_monitoring-net:

volumes:
  qw_dev_logs: